import { Lead, ChatSession, ScheduledVisit, AgencyStats } from './types';

export const INITIAL_STATS: AgencyStats = {
  leadsToday: 24,
  leadsThisMonth: 412,
  qualifiedRate: 74,
  discardedCuriososRate: 58,
  visitsScheduledThisMonth: 86,
  avgResponseTimeSeconds: 4.8,
  hoursSavedMonthly: 142,
};

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-01',
    name: 'Carlos Mendoza',
    phone: '+34 612 849 201',
    email: 'carlos.mendoza@inversionescm.es',
    channel: 'WhatsApp',
    propertyTitle: 'Ático Dúplex con Terraza Panorámica',
    propertyRef: 'MAD-SAL-042',
    propertyPrice: '620.000 €',
    budget: '650.000 €',
    mortgageStatus: 'Al contado (Sin hipoteca)',
    urgency: 'Inmediata (< 15 días)',
    score: 98,
    status: 'cita_agendada',
    createdAt: 'Hoy, 10:14',
    visitScheduledAt: 'Mañana, 17:30 - Asignado a Elena Ruiz',
    assignedAgent: 'Elena Ruiz (Senior Broker)',
    aiSummary: 'Comprador directo con capital disponible en cuenta. Busca vivienda habitual para entrar antes de fin de mes. Muy receptivo y con capacidad de reserva inmediata.',
  },
  {
    id: 'lead-02',
    name: 'Beatriz y David Gómez',
    phone: '+34 645 221 908',
    email: 'beatriz.gomez@gmail.com',
    channel: 'Idealista',
    propertyTitle: 'Piso Señorial Reformado en Chamberí',
    propertyRef: 'MAD-CHB-119',
    propertyPrice: '485.000 €',
    budget: '500.000 €',
    mortgageStatus: 'Preaprobada',
    urgency: '1 a 3 meses',
    score: 91,
    status: 'cita_agendada',
    createdAt: 'Hoy, 08:42',
    visitScheduledAt: 'Viernes, 12:00 - Asignado a Marcos Varela',
    assignedAgent: 'Marcos Varela',
    aiSummary: 'Pareja con hipoteca preconcedida en BBVA por 380k + 120k en fondos propios. Buscan piso con ascensor y 3 habitaciones.',
  },
  {
    id: 'lead-03',
    name: 'Javier Sanjurjo',
    phone: '+34 699 104 553',
    email: 'j.sanjurjo@abogados.com',
    channel: 'Fotocasa',
    propertyTitle: 'Villa Exclusiva con Piscina Privada',
    propertyRef: 'VAL-CAN-802',
    propertyPrice: '890.000 €',
    budget: '950.000 €',
    mortgageStatus: 'Preaprobada',
    urgency: '1 a 3 meses',
    score: 87,
    status: 'calificado',
    createdAt: 'Hoy, 12:05',
    assignedAgent: 'Laura Montero',
    aiSummary: 'Inversor residencial buscando segunda residencia. Cualificado con solvencia comprobada. Pendiente de cuadrar agenda de visita con su socia para el fin de semana.',
  },
  {
    id: 'lead-04',
    name: 'Lucía Morales',
    phone: '+34 633 481 092',
    email: 'lucia.morales@techhub.io',
    channel: 'Web Chat',
    propertyTitle: 'Loft Minimalista Industrial en Poblenou',
    propertyRef: 'BCN-POB-331',
    propertyPrice: '395.000 €',
    budget: '410.000 €',
    mortgageStatus: 'En trámite',
    urgency: 'Inmediata (< 15 días)',
    score: 84,
    status: 'en_conversacion',
    createdAt: 'Hoy, 14:28',
    assignedAgent: 'Elena Ruiz',
    aiSummary: 'Interesada en compra antes de renovación de alquiler actual en 2 meses. El agente IA está esperando su confirmación de franja horaria preferida.',
  },
  {
    id: 'lead-05',
    name: 'Rodrigo Peña',
    phone: '+34 670 993 118',
    email: 'r.pena28@hotmail.com',
    channel: 'Idealista',
    propertyTitle: 'Ático Dúplex con Terraza Panorámica',
    propertyRef: 'MAD-SAL-042',
    propertyPrice: '620.000 €',
    budget: '290.000 €',
    mortgageStatus: 'Sin estudiar / Sin ahorros',
    urgency: 'Solo curioseando',
    score: 22,
    status: 'descartado',
    reasonIfDiscarded: 'Presupuesto insuficiente (290k vs 620k del inmueble) y sin estudio bancario. Preguntó si se alquila con opción a compra.',
    createdAt: 'Ayer, 23:14',
    assignedAgent: 'Filtro Automático Propia',
    aiSummary: 'Filtro automático ejecutado con éxito. Se le envió mensaje cordial informando que el inmueble excede su búsqueda, ahorrando 1 hora de visita desierta al comercial.',
  },
  {
    id: 'lead-06',
    name: 'Marta Soler',
    phone: '+34 651 882 309',
    email: 'marta.soler@consultora.es',
    channel: 'WhatsApp',
    propertyTitle: 'Piso Señorial Reformado en Chamberí',
    propertyRef: 'MAD-CHB-119',
    propertyPrice: '485.000 €',
    budget: 'Sin especificar',
    mortgageStatus: 'Sin estudiar / Sin ahorros',
    urgency: 'Solo curioseando',
    score: 30,
    status: 'descartado',
    reasonIfDiscarded: 'Curioso sin intención de compra. Indicó que solo quería ver la decoración de las fotos para reformar su propia casa.',
    createdAt: 'Ayer, 18:30',
    assignedAgent: 'Filtro Automático Propia',
    aiSummary: 'Detectado perfil no comprador tras 3 preguntas de filtro. No se consumió tiempo de comercial ni se bloqueó agenda.',
  }
];

export const INITIAL_CHATS: ChatSession[] = [
  {
    id: 'chat-01',
    leadId: 'lead-01',
    leadName: 'Carlos Mendoza',
    phone: '+34 612 849 201',
    propertyTitle: 'Ático Dúplex con Terraza Panorámica (Ref: MAD-SAL-042)',
    propertyRef: 'MAD-SAL-042',
    channel: 'WhatsApp',
    status: 'cita_agendada',
    score: 98,
    lastMessage: 'Perfecto, visita confirmada para mañana a las 17:30 con Elena Ruiz. Te acabo de enviar la ubicación exacta por WhatsApp y la invitación a tu calendario.',
    lastActivity: 'Hace 12 min',
    qualificationSummary: {
      budget: '650.000 € (Precio inmueble: 620.000 €)',
      financing: '100% fondos propios disponibles',
      urgency: 'Compra en menos de 2 semanas',
      intent: 'Vivienda habitual premium',
      score: 98,
    },
    messages: [
      {
        id: 'm-1',
        sender: 'lead',
        text: 'Hola buenas tardes, he visto vuestro anuncio del ático dúplex en Salamanca por 620.000€. ¿Sigue disponible? Me gustaría ir a verlo.',
        timestamp: '10:14:02',
      },
      {
        id: 'm-2',
        sender: 'agent',
        text: '¡Hola Carlos! Sí, el ático dúplex en calle Claudio Coello sigue disponible. Soy Valeria de Propia, asistente inmobiliaria de la agencia. ¿Estarías buscando adquirirlo como vivienda habitual o como inversión patrimonial?',
        timestamp: '10:14:08',
        badge: 'Respuesta en 6 seg',
      },
      {
        id: 'm-3',
        sender: 'lead',
        text: 'Sería para mudarme con mi familia. Actualmente vivimos de alquiler en la zona y queremos comprar ya.',
        timestamp: '10:14:45',
      },
      {
        id: 'm-4',
        sender: 'agent',
        text: 'Entendido, es una zona fantástica. Para asegurarnos de que la visita sea 100% productiva para ti: el precio es de 620.000 €. ¿Cuentas con la financiación ya preaprobada o dispones de fondos propios para la operación?',
        timestamp: '10:14:52',
        badge: 'Cualificación de solvencia',
      },
      {
        id: 'm-5',
        sender: 'lead',
        text: 'Tengo los fondos disponibles en cuenta bancaria, no necesito hipoteca para este importe.',
        timestamp: '10:15:30',
      },
      {
        id: 'm-6',
        sender: 'agent',
        text: 'Excelente, Carlos. Al no depender de hipoteca el proceso de arras y firma puede ser muy ágil. Nuestra especialista en Salamanca, Elena Ruiz, tiene dos huecos exclusivos mañana: a las 11:30 o a las 17:30. ¿Cuál te encajaría mejor?',
        timestamp: '10:15:37',
        badge: 'Sincronización de Agenda',
      },
      {
        id: 'm-7',
        sender: 'lead',
        text: 'Por la tarde me viene genial, a las 17:30.',
        timestamp: '10:16:10',
      },
      {
        id: 'm-8',
        sender: 'agent',
        text: 'Perfecto, Carlos. Queda agendada tu visita para mañana a las 17:30 con Elena Ruiz. Te acabo de reservar el espacio y te llegará la cita a tu calendario junto con la ficha catastral detallada.',
        timestamp: '10:16:16',
        badge: 'Cita Agendada en Google Calendar',
      },
    ],
  },
  {
    id: 'chat-05',
    leadId: 'lead-05',
    leadName: 'Rodrigo Peña',
    phone: '+34 670 993 118',
    propertyTitle: 'Ático Dúplex con Terraza Panorámica (Ref: MAD-SAL-042)',
    propertyRef: 'MAD-SAL-042',
    channel: 'Idealista',
    status: 'descartado',
    score: 22,
    lastMessage: 'He guardado tus datos por si captamos alguna vivienda en tu rango de 290.000 €. ¡Muchas gracias por tu interés!',
    lastActivity: 'Ayer, 23:16',
    qualificationSummary: {
      budget: '290.000 € (Inmueble: 620.000 €)',
      financing: 'Sin fondos ni estudio bancario',
      urgency: 'Solo sondeando',
      intent: 'Curioso / No viable',
      score: 22,
    },
    messages: [
      {
        id: 'cm-1',
        sender: 'lead',
        text: 'Hola, me encanta el ático. ¿Se puede negociar el precio a la mitad o hacer alquiler con opción a compra con 1.000€ al mes?',
        timestamp: '23:14:10',
      },
      {
        id: 'cm-2',
        sender: 'agent',
        text: '¡Buenas noches Rodrigo! Gracias por tu contacto. Esta propiedad tiene un precio de venta fijado de 620.000 € y la propiedad no contempla alquiler con opción a compra. ¿Cuál es tu presupuesto máximo de compra y situación de hipoteca?',
        timestamp: '23:14:15',
        badge: 'Filtro de condiciones',
      },
      {
        id: 'cm-3',
        sender: 'lead',
        text: 'Mi tope serían unos 280k o 290k con suerte si el banco me da el 100%. Solo quería curiosear a ver si colaba.',
        timestamp: '23:15:30',
      },
      {
        id: 'cm-4',
        sender: 'agent',
        text: 'Te agradecemos mucho la sinceridad, Rodrigo. Para no hacerte perder tiempo en una visita a una vivienda que excede tu rango objetivo, hemos guardado tus criterios en nuestra base de datos. Si entra un inmueble dentro de tu presupuesto de 290.000 €, te avisaremos de inmediato.',
        timestamp: '23:15:38',
        badge: 'Curioso descartado cordialmente',
      },
    ],
  },
  {
    id: 'chat-02',
    leadId: 'lead-02',
    leadName: 'Beatriz Gómez',
    phone: '+34 645 221 908',
    propertyTitle: 'Piso Señorial Reformado en Chamberí (Ref: MAD-CHB-119)',
    propertyRef: 'MAD-CHB-119',
    channel: 'Idealista',
    status: 'cita_agendada',
    score: 91,
    lastMessage: 'Cita programada para este viernes a las 12:00 con Marcos Varela.',
    lastActivity: 'Hoy, 08:45',
    qualificationSummary: {
      budget: '500.000 € (Precio inmueble: 485.000 €)',
      financing: 'Hipoteca preaprobada en BBVA (380k + 120k ahorros)',
      urgency: '1 a 3 meses',
      intent: 'Compra familiar confirmada',
      score: 91,
    },
    messages: [
      {
        id: 'bm-1',
        sender: 'lead',
        text: 'Hola, querríamos información del piso en Chamberí reformado. Somos una pareja interesada en visitarlo esta semana.',
        timestamp: '08:42:01',
      },
      {
        id: 'bm-2',
        sender: 'agent',
        text: '¡Hola Beatriz! Encantada de saludarte. Es una vivienda impecable de 115m², 3 dormitorios y finca clásica. ¿Tenéis ya estudiada la parte financiera o contáis con hipoteca aprobada para el importe de 485.000 €?',
        timestamp: '08:42:07',
        badge: 'Cualificación financiera',
      },
      {
        id: 'bm-3',
        sender: 'lead',
        text: 'Sí, tenemos el FEIN preliminar de BBVA por 380.000€ y aportamos 120.000€ de ahorros nuestros demostrables.',
        timestamp: '08:43:12',
      },
      {
        id: 'bm-4',
        sender: 'agent',
        text: '¡Excelente viabilidad! Vuestro perfil encaja a la perfección con la propiedad. ¿Qué día os vendría mejor para hacer la visita con nuestro asesor de Chamberí, Marcos Varela? Tenemos disponibilidad este viernes a las 12:00 o a las 16:30.',
        timestamp: '08:43:18',
        badge: 'Lead Calificado VIP',
      },
      {
        id: 'bm-5',
        sender: 'lead',
        text: 'El viernes a las 12:00 nos viene de maravilla.',
        timestamp: '08:44:05',
      },
      {
        id: 'bm-6',
        sender: 'agent',
        text: 'Agendado. Marcos os recibirá en el portal a las 12:00 en punto. Os hemos enviado el recordatorio a vuestro correo y WhatsApp.',
        timestamp: '08:44:11',
        badge: 'Visita Agendada',
      },
    ],
  },
];

export const INITIAL_VISITS: ScheduledVisit[] = [
  {
    id: 'vis-01',
    leadName: 'Carlos Mendoza',
    leadPhone: '+34 612 849 201',
    propertyTitle: 'Ático Dúplex con Terraza Panorámica',
    propertyRef: 'MAD-SAL-042',
    propertyAddress: 'Calle Claudio Coello 84, 6º Ext, Madrid',
    dateTime: 'Mañana, 17:30',
    assignedAgent: 'Elena Ruiz (Senior Broker)',
    status: 'Confirmada',
    buyerProfile: 'Comprador sin hipoteca (Fondos en cuenta)',
    budget: '650.000 €',
  },
  {
    id: 'vis-02',
    leadName: 'Beatriz y David Gómez',
    leadPhone: '+34 645 221 908',
    propertyTitle: 'Piso Señorial Reformado en Chamberí',
    propertyRef: 'MAD-CHB-119',
    propertyAddress: 'Calle Santa Engracia 42, 3º Dcha, Madrid',
    dateTime: 'Viernes, 12:00',
    assignedAgent: 'Marcos Varela',
    status: 'Confirmada',
    buyerProfile: 'Hipoteca BBVA Preaprobada (380k + 120k)',
    budget: '500.000 €',
  },
  {
    id: 'vis-03',
    leadName: 'Guillermo Alarcón',
    leadPhone: '+34 688 331 445',
    propertyTitle: 'Casa Unifamiliar en La Moraleja',
    propertyRef: 'MAD-MOR-902',
    propertyAddress: 'Paseo del Conde 14, Alcobendas',
    dateTime: 'Sábado, 11:00',
    assignedAgent: 'Elena Ruiz',
    status: 'Recordatorio enviado',
    buyerProfile: 'Inversor patrimonial (VIP)',
    budget: '1.450.000 €',
  },
  {
    id: 'vis-04',
    leadName: 'Sonia Garrido',
    leadPhone: '+34 622 901 118',
    propertyTitle: 'Bajo con Jardín Privado en Retiro',
    propertyRef: 'MAD-RET-077',
    propertyAddress: 'Avenida Menéndez Pelayo 29, Madrid',
    dateTime: 'Lunes, 16:00',
    assignedAgent: 'Laura Montero',
    status: 'Pendiente reconfirmación',
    buyerProfile: 'Compra de reposición (Piso anterior vendido)',
    budget: '550.000 €',
  }
];
